import type { Product, Category } from './types';
export const CATEGORIES: Category[] = [
  "Application Security and Performance",
  "Network Security and Connectivity",
  "Zero Trust",
  "Developer Services",
];
export const products: Product[] = [
  {
    id: 'prod_001',
    name: 'WAF (Web Application Firewall)',
    description: 'Protect your applications from malicious traffic, including SQL injection and cross-site scripting.',
    icon: 'ShieldCheck',
    categories: ['Application Security and Performance'],
    cost: 3,
    difficulty: 25,
  },
  {
    id: 'prod_002',
    name: 'CDN (Content Delivery Network)',
    description: 'Cache content closer to your users to accelerate your website and reduce bandwidth costs.',
    icon: 'Globe',
    categories: ['Application Security and Performance'],
    cost: 2,
    difficulty: 15,
  },
  {
    id: 'prod_003',
    name: 'Magic Transit',
    description: 'On-demand DDoS protection for your network infrastructure, delivered from the Cloudflare edge.',
    icon: 'Router',
    categories: ['Network Security and Connectivity'],
    cost: 5,
    difficulty: 70,
  },
  {
    id: 'prod_004',
    name: 'Cloudflare Access',
    description: 'A Zero Trust Network Access (ZTNA) solution to secure access to internal applications.',
    icon: 'KeyRound',
    categories: ['Zero Trust'],
    cost: 2,
    difficulty: 40,
  },
  {
    id: 'prod_005',
    name: 'Workers',
    description: 'Deploy serverless code instantly across the globe to give it exceptional performance, reliability, and scale.',
    icon: 'Code',
    categories: ['Developer Services'],
    cost: 1,
    difficulty: 30,
  },
  {
    id: 'prod_006',
    name: 'R2 Storage',
    description: 'Globally distributed object storage without the egress fees. Ideal for CDN assets and application data.',
    icon: 'Database',
    categories: ['Developer Services'],
    cost: 1,
    difficulty: 20,
  },
  {
    id: 'prod_007',
    name: 'DDoS Protection',
    description: 'Always-on, unmetered DDoS mitigation for layers 3, 4, and 7, powered by our global network.',
    icon: 'ShieldAlert',
    categories: ['Application Security and Performance', 'Network Security and Connectivity'],
    cost: 4,
    difficulty: 10,
  },
  {
    id: 'prod_008',
    name: 'Cloudflare Gateway',
    description: 'A secure web gateway (SWG) to protect users from malware, phishing, and other Internet threats.',
    icon: 'Network',
    categories: ['Zero Trust'],
    cost: 2,
    difficulty: 50,
  },
  {
    id: 'prod_009',
    name: 'Magic WAN',
    description: 'A cloud-native replacement for legacy WAN architectures, connecting and securing your corporate network.',
    icon: 'Waypoints',
    categories: ['Network Security and Connectivity'],
    cost: 4,
    difficulty: 85,
  },
  {
    id: 'prod_010',
    name: 'Pages',
    description: 'A fast, secure, and scalable platform for frontend developers to build and deploy JAMstack websites.',
    icon: 'FileCode',
    categories: ['Developer Services'],
    cost: 1,
    difficulty: 5,
  },
  {
    id: 'prod_011',
    name: 'Bot Management',
    description: 'Detect and mitigate bad bots with machine learning, while allowing good bots to pass through.',
    icon: 'Bot',
    categories: ['Application Security and Performance'],
    cost: 4,
    difficulty: 35,
  },
  {
    id: 'prod_012',
    name: 'D1 Database',
    description: 'The worlds first serverless SQL database, built on SQLite and integrated with Cloudflare Workers.',
    icon: 'DatabaseZap',
    categories: ['Developer Services'],
    cost: 2,
    difficulty: 45,
  },
];